openapi: 3.1.0
info:
  title: Task2 API
  version: '1.0'
  description: Image Recognition task
servers:
  - url: 'https://wjevk3l5ai.execute-api.us-east-1.amazonaws.com/dev/'
    description: dev
paths:
  /blobs/:
    parameters: []
    get:
      summary: ''
      operationId: get-blobs-results
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  Count:
                    type: string
                    minLength: 1
                  Items:
                    type: array
                    items:
                      required: []
                      properties: {}
                  ScannedCount:
                    type: string
                    minLength: 1
                required:
                  - Count
                  - Items
                  - ScannedCount

        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  exception:
                    type: string
              examples: {}
        '':
          description: ''
      description: 'get the image recognition jobs results '
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
        description: ''
      parameters:
        - schema:
            type: string
          in: query
          name: blob_id
          description: the id of the blob item
  /reqUrl:
    post:
      summary: 'request a presigned url from lambda function'
      operationId: request-url
      responses:
        '200':
          description: 'OK, blob created successfully'
          content:
            application/json:
              schema:
                type: object
                properties:
                  presigned_url:
                    type: string
                  jpg_presigned_upload_url:
                     type: string
                  png_presigned_upload_url: 
                     type: string  
                  error_message:
                    type: string



        '400':
          description: 'Bad Request '
          content:
            application/json:
              schema:
                type: object
                properties:
                  exception:
                    type: string
      description: request a presigned url
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                callback_url:
                  type: string
                file_name:
                  type: string  
        description: optional call back url and file name

